# shopify.app.toml

name = "bot-protection-app-fixed"
client_id = "5e0b45e5abe855d21a409ca713edf9e6"
application_url = "https://bot-protection-ten.vercel.app"
embedded = true

[auth]
redirect_urls = [
  "https://bot-protection-ten.vercel.app/auth/callback",
  "https://bot-protection-ten.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

# ここから Admin Link Extensions
[[extensions]]
name = "IP追加"
handle = "add-ip"
type = "admin_link"
destination = "/admin/add-ip"

[[extensions]]
name = "ブロックリスト"
handle = "list-ip"
type = "admin_link"
destination = "/admin/list-ip"

[[extensions]]
name = "アクセスログ"
handle = "logs"
type = "admin_link"
destination = "/admin/logs"
